name: Repository Drift Detection

on:
  pull_request:
    paths:
      - 'REPOSITORIES.md'
      - 'scripts/**'
      - '.github/workflows/drift-detection.yml'

jobs:
  detect-drift:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Make scripts executable
        run: chmod +x scripts/*.js

      - name: Run drift detection
        id: drift
        env:
          WORLDDRIVEN_GITHUB_TOKEN: ${{ secrets.WORLDDRIVEN_GITHUB_TOKEN }}
        run: |
          set +e
          node scripts/detect-drift.js > drift-report.md 2>&1
          EXIT_CODE=$?
          echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
          set -e
        continue-on-error: true

      - name: Comment PR with drift report
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('drift-report.md', 'utf8');

            // Find existing comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(comment =>
              comment.user.type === 'Bot' &&
              comment.body.includes('Repository Drift Report')
            );

            const commentBody = `${report}\n\n---\n*🤖 This report is automatically generated on every PR that modifies REPOSITORIES.md*`;

            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: commentBody,
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody,
              });
            }

      - name: Check drift detection result
        if: steps.drift.outputs.exit_code != '0'
        run: |
          echo "⚠️ Drift detected between REPOSITORIES.md and GitHub organization"
          echo "Review the drift report in the PR comment above"
          exit 0
